version: "3"
services:
    node9:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-9
        ports:
            - "4209:80"
        command: "npm run test:ci"
    node8:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-8
        ports:
            - "4209:80"
        command: "npm run test:ci"
    node6:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-6
        ports:
            - "4209:80"
        command: "npm run test:ci"
