FROM node:6

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app

RUN apt-get update \
    && apt-get install -y chromium

ENV CHROME_BIN=chromium

RUN npm install

COPY . .

CMD [ "npm", "start" ]
